apiVersion: v1
kind: Service
metadata:
  name: {{ include "flask-app.fullname" . }}
spec:
  type: NodePort
  selector:
    app: {{ include "flask-app.name" . }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: {{ .Values.service.nodePort }}
